analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: localhost
      port: 9000  # Native protocol
      http_port: 8123  # HTTP protocol
      user: admin
      password: password
      database: ticket_pricing
      schema: ticket_pricing  # ClickHouse uses database as schema
      # cluster: analytics_cluster  # For distributed setups
      secure: false  # True for production
      verify: false  # SSL verification
      connect_timeout: 10
      send_receive_timeout: 300
      sync_request_timeout: 5